#!/bin/bash

OUTPUT_FILE="cache_types.go"
IMPORTS_FILE="${OUTPUT_FILE}.template.1"
STRUCTS_FILE="${OUTPUT_FILE}.template.3"
CACHE_MAIN_DIR="github.com/ironsmile/nedomi/cache"


echo "Generating $OUTPUT_FILE..."

echo -n > "$IMPORTS_FILE"
echo -n > "$STRUCTS_FILE"

CACHE_TYPES=`ls -p | grep '/' | sed 's/\///'`

for CACHE_TYPE in $CACHE_TYPES; do
    echo "\"$CACHE_MAIN_DIR/$CACHE_TYPE\"" >> "$IMPORTS_FILE"
    echo -e "\"$CACHE_TYPE\": func(cz *config.CacheZoneSection) CacheManager {\nreturn $CACHE_TYPE.New(cz)\n},\n" >> "$STRUCTS_FILE"
done

cat "${OUTPUT_FILE}.template.0" "$IMPORTS_FILE" "${OUTPUT_FILE}.template.2" \
    "$STRUCTS_FILE" "${OUTPUT_FILE}.template.4" > "$OUTPUT_FILE"

go fmt "$OUTPUT_FILE"

echo "Done"
